name = "TailRec"
uuid = "f6209947-f0a9-4a6b-8802-d6ceac74b6f9"
authors = ["Takekazu KATO <takekazu.kato@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
